import { SpeedInsights } from '@vercel/speed-insights/next';

import Navbar from "@/components/navbar";

import { paragraphFont } from "@/utils/fonts";
import "./globals.css";

export const metadata = {
  title: "Voyage de la Lune Hackathon",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={paragraphFont.className}>
        <Navbar />
        {children}
        <SpeedInsights />
      </body>
    </html>
  );
}
